### PR TITLE
Add model files of BoostedDeepTauID v2.0

### PR DESCRIPTION
**Pull request by mbluj**
As title says, this PR adds model files of BoostedDeepTauID v2.0.
PR to CMSSW with code using the model files is https://github.com/cms-sw/cmssw/pull/46112.

### CODE REVIEW

**Comment by mbluj** [comment]
PR to CMSSW depending on model files in this PR is https://github.com/cms-sw/cmssw/pull/46112.

**Comment by mandrenguyen** [comment]
ping @cms-sw/reconstruction-l2 @cms-sw/externals-l2

**Comment by jfernan2** [comment]
+1

**Comment by smuzaffar** [comment]
+externals

only new files and tested via https://github.com/cms-sw/cmssw/pull/46112

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge

**Pull request merged**
