### PR TITLE
Remove model files of depreciated tauIds.

### PR DESCRIPTION
**Pull request by mbluj**
As title says, this PR removes model files of depreciated tauIds: DPFIsolation v0 and v1, and DeepTauId v1.
This PR complements https://github.com/cms-sw/cmssw/pull/38063.

### CODE REVIEW

**Comment by perrotta** [comment]
please test with https://github.com/cms-sw/cmssw/pull/38063

**Comment by perrotta** [comment]
Differences in reco outputs are due to the additional merge commits added while running this PR.
The important thing is that nothing crashes when running this together with https://github.com/cms-sw/cmssw/pull/38063

Please @cms-sw/reconstruction-l2 have a look and sign, if you have nothing against this removal of now unused data files

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
@jpata @clacaputo : it is certainly not urgent, but if you agree with removing those data files after the removal of the tauIds which were using them (by the already merged https://github.com/cms-sw/cmssw/pull/38164), please let us know by signing this PR

**Comment by perrotta** [comment]
+1

**Pull request merged**
