### PR TITLE
DeepTau2017v2 without memory mapping

### PR DESCRIPTION
**Pull request by mbluj**
DeepTau: Switched to split training files without memory mapping to be compatible with TensorFlow 2.1 as in PR https://github.com/cms-sw/cmssw/pull/28711. To be propagated to cmsdist together with TF2.1.

It was tested with CMSSW_11_1_X (still with TF1.x) using 1k ttbar events (~3.5k tau candidates) that deepTau with training files with and without memory mapping gives exactly same results (as expected).

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals
looks good, unit tests failures are not due to this chage. Looks like there is issue with Frontier server.
Can you move forward with the integration of TF 2.1 ?

**Comment by silviodonato** [comment]
@perrotta @slava77 This is the cms-data PR I mentioned during the ORP meeting.

**Comment by perrotta** [comment]
+1
- Modifications to the binary files have been tested and evaluated together with #28711 and look like being able to allow moving to TF 2.1 in CMSSW

**Comment by silviodonato** [comment]
+1

**Comment by mrodozov** [comment]
@silviodonato I'm merging the consequent cmsdist PR to include this change.

**Comment by silviodonato** [comment]
Thanks @mrodozov , I thought every changes in cmsdist were already included in cms-sw/cmsdist#5525 . Do you know why the tests were ok, even without cms-sw/cmsdist#5601?

**Comment by mrodozov** [comment]
when you are testing with additional PRs they are explicitly taken and used, in this case this PR overwrites the previous version (i.e. RecoTauTag-TrainingFiles=V00-01-01) for this data external. Additional PRs are doing temporarily (during testing) what cms-sw/cmsdist#5601 did permanently

**Comment by silviodonato** [comment]
Thank you @mrodozov !

**Pull request merged**
