### PR TITLE
Training file for DeepTauID 2017v2

### PR DESCRIPTION
**Pull request by mbluj**
As title says, this PR adds a training file for DeepTauID version 2017v2.

### CODE REVIEW

**Comment by mbluj** [comment]
All Unit Test with errors failed due to problem with access to input files.

**Comment by smuzaffar** [comment]
+externals

**Comment by mbluj** [comment]
Training files for cms-sw/cmssw#26796 updated to improve CPU timing:
* Split network into 3 parts: inner, outer and core.
* Previous training file has been removed.

**Comment by fabiocos** [comment]
@perrotta I understand this is ok for RECO, in case please sign it

**Comment by fabiocos** [comment]
@mbluj @smuzaffar this needs to be added to cmsdist as a new tag, right?

**Comment by mbluj** [comment]
> 
> 
> @mbluj @smuzaffar this needs to be added to cmsdist as a new tag, right?

I think so.

**Comment by perrotta** [comment]
+1
- New training files added, as needed by #26796

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
@fabiocos , https://github.com/cms-sw/cmsdist/pull/5026 includes these new files for cmssw 11.0.X. As this only adds new files, so we have merged it for next IB.

**Comment by fabiocos** [comment]
+1

@smuzaffar thank you a lot !

**Pull request merged**
