### PR TITLE
Add models for DeepTauID v2p5

### PR DESCRIPTION
**Pull request by mbluj**
This PR adds models (training files) for DeepTauId v2p5 based on UL2018 samples (called 2018v2p5).
This PR is related to https://github.com/cms-sw/cmssw/pull/37892.

### CODE REVIEW

**Comment by jpata** [comment]
just to make sure: the old files still have to be kept because they are being used?

**Comment by mbluj** [comment]
> just to make sure: the old files still have to be kept because they are being used?

Yes, it is correct. However we plan to remove older than v2 versions of DNN-based tauIDs which will allow removal of corresponding model files.

**Comment by kandrosov** [comment]
DeepTau v2p1 will be supported until the SFs for v2p5 are available for both Run2 and Run3. So at least until summer 2023.
On the other hand, DeepTau v1 and DPFTauId (and corresponding code in CMSSW) can be already removed. We plan to do it in the next few months.

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/37892#issuecomment-1124079697

**Comment by smuzaffar** [comment]
+externals
- contains only new files so should be safe to include.
- already tested via https://github.com/cms-sw/cmssw/pull/37892.

**Comment by perrotta** [comment]
+1
- Only new files added
- Anyhow tested together with #37892

**Pull request merged**
