### PR TITLE
New DeepTauID v2p5 model

### PR DESCRIPTION
**Pull request by mbluj**
This PR replaces an initial DeepTauID_v2p5 model files by new ones.

The performance of the initial DeepTau v2p5 and the new (current) v2p5 model are roughly comparable, the main improvement is data-MC agreement at high VSjet bins (e.g. [here](https://indico.cern.ch/event/1164900/contributions/4891675/attachments/2450061/4198838/TauML_adversarial_2405.pdf#page=4)). This type of disagreement is present also for older tauIDs, namely DeepTau v2p1 and old BDT-based MVA-iso.

Full set of results of performance study on Run-2 and Run-3 samples can be found under the following link: https://indico.cern.ch/event/1164900/contributions/4891675/attachments/2450061/4204746/FinalModel.pdf, while result of a study of base models performance (used as a starting point) here: https://indico.cern.ch/event/1164900/contributions/4891675/attachments/2450061/4205013/deeptauv2p5_run2_run3_sample_comparison.pdf.

The new files are added on top of development branch removing old tauID models as in PR https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9, so the removal is also seen here as https://github.com/cms-data/RecoTauTag-TrainingFiles/pull/9 is not merged, yet.

This PR is intended to be propagated to cms-data for both master and 12_4_X.

### CODE REVIEW

**Comment by kandrosov** [comment]
@jpata @clacaputo A kind reminder that from the tau POG side, we would like to have these final DeepTau v2p5 training files updated in this PR for both 12_4 and 12_5 CMSSW distributions. Please, let us know if there is an issue preventing this PR from being merged. Thank you!

**Comment by jpata** [comment]
Can you post some information on CPU/MEM profiling with the new models? I'm not sure if the bot is able to do it if it's not attached to a cms-sw/cmssw PR.

**Comment by kandrosov** [comment]
> Can you post some information on CPU/MEM profiling with the new models? I'm not sure if the bot is able to do it if it's not attached to a cms-sw/cmssw PR.

can it be tested together with this PR https://github.com/cms-sw/cmssw/pull/38164 ? But if you think it would be too messy, we can do CPU/MEM test manually, of course.

**Comment by jpata** [comment]
> We announced this at the same OP meeting where the faith of PR with v2p5 code was discussed. 

Right, I just wanted to have this clearly in writing here as well for the future.

> can it be tested together with this PR

It looks like the profiling was not successful in the other PR. Can you estimate if the model structure changed significantly since the last version (ops, number of parameters)? If not, then likely there is no measurable effect on profiling and we can proceed.

**Comment by jpata** [comment]
@cmsbuild please test

**Comment by kandrosov** [comment]
> Can you estimate if the model structure changed significantly since the last version (ops, number of parameters)?

The network layout  (including the number operations and trainable parameters) is exactly the same as in the "placeholder" model. The only thing which is changed is the numerical values of weights. So we don't expect any change in memory consumption or CPU performance.

**Comment by jpata** [comment]
+reconstruction
- new tauID model files
- no effect on computational performance is expected
- small changes to tau IDs expected (and nothing else)

**Comment by jpata** [comment]
Once this is merged, the new tag should be propagated also for 12_4_X at https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_12_4_X/master/data/cmsswdata.txt#L34.

**Comment by kandrosov** [comment]
@smuzaffar, @perrotta, @dpiparo, @qliphy is there some additional input from the Tau POG side to merge this PR and propagate it to 12_4_X? 
My apologies for being a bit pushy, but we (tau developers) do not want to miss the 12_4_0 deadline as it happened with pre4 :)

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
